export enum RevenueCatWebhookEventTypes {
  Test = 'TEST',
  InitialPurchase = 'INITIAL_PURCHASE',
  NonRenewingPurchase = 'NON_RENEWING_PURCHASE',
  Renewal = 'RENEWAL',
  ProductChange = 'PRODUCT_CHANGE',
  Cancellation = 'CANCELLATION',
  BillingIssue = 'BILLING_ISSUE',
  SubscriberAlias = 'SUBSCRIBER_ALIAS',
  SubscriptionPaused = 'SUBSCRIPTION_PAUSED',
  Uncancellation = 'UNCANCELLATION',
  Transfer = 'TRANSFER',
  SubscriptionExtended = 'SUBSCRIPTION_EXTENDED',
  Expiration = 'EXPIRATION',
  TemporaryEntitlementGrant = 'TEMPORARY_ENTITLEMENT_GRANT',
  InvoiceIssuance = 'INVOICE_ISSUANCE',
  VirtualCurrencyTransaction = 'VIRTUAL_CURRENCY_TRANSACTION',
  ExperimentEnrollment = 'EXPERIMENT_ENROLLMENT',
}
