export const DOMAIN_EVENT_HANDLER_METADATA_KEY =
  'DOMAIN_EVENT_HANDLER_METADATA_KEY';
export const EVENT_PAYLOAD_PARAM = 'EVENT_PAYLOAD_PARAM';
export const EVENT_TRANSACTION_PARAM = 'EVENT_TRANSACTION_PARAM';
export const EVENT_PARAM = 'EVENT_PARAM';
export const EVENT_NAME_PARAM = 'EVENT_NAME_PARAM';
